### ISSUE TITLE
Milestone 1 Checklist

### ISSUE THREAD

**Issue by karan-khubdikar** [UBC-MDS/DSCI-532_2024_13_appname#12]
Creating the Milestone 1 checklist. We can tick off the checklist as and when we complete it.
- [ ] Motivation and purpose
- [ ] Description of the data
- [ ] Research questions
- [ ] App sketch and description
